[package]
name = "git-gen-git"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
git-gen-core = { path = "../core" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
